cloud:
  aws:
    credentials:
      access-key: AKIAVZ2MSLM77IFMJM6E
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false
      


application:
  bucket:
    name: ashrafalam
    
server:
  port: 4000